using System;
using System.IO;
using Xunit;
using QR;

namespace QRCode_POC.Tests;

public class QRCodeServiceTests
{
    private readonly QRCodeService _qrCodeService;

    public QRCodeServiceTests()
    {
        _qrCodeService = new QRCodeService();
    }

    [Fact]
    public void GenerateQRCode_WithValidInput_ReturnsFilePath()
    {
        // Arrange
        string name = "John Doe";
        string email = "john.doe@example.com";
        DateTime dateOfBirth = new DateTime(1990, 5, 15);

        // Act
        string filePath = _qrCodeService.GenerateQRCode(name, email, dateOfBirth);

        // Assert
        Assert.NotNull(filePath);
        Assert.NotEmpty(filePath);
        Assert.Contains("QRCode_", filePath);
        Assert.EndsWith(".png", filePath);

        // Cleanup
        if (File.Exists(filePath))
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void GenerateQRCode_CreatesPhysicalFile()
    {
        // Arrange
        string name = "Jane Smith";
        string email = "jane.smith@example.com";
        DateTime dateOfBirth = new DateTime(1985, 3, 20);

        // Act
        string filePath = _qrCodeService.GenerateQRCode(name, email, dateOfBirth);

        // Assert
        Assert.True(File.Exists(filePath), $"File {filePath} was not created");
        Assert.True(new FileInfo(filePath).Length > 0, "Generated file is empty");

        // Cleanup
        if (File.Exists(filePath))
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void GenerateVCard_WithValidInput_ReturnsVCardFormat()
    {
        // Arrange
        string name = "Test User";
        string email = "test@example.com";
        DateTime dateOfBirth = new DateTime(1990, 1, 1);

        // Act
        string vCard = _qrCodeService.GenerateVCard(name, email, dateOfBirth);

        // Assert
        Assert.NotNull(vCard);
        Assert.Contains("BEGIN:VCARD", vCard);
        Assert.Contains("END:VCARD", vCard);
        Assert.Contains("VERSION:3.0", vCard);
        Assert.Contains($"FN:{name}", vCard);
        Assert.Contains($"EMAIL:{email}", vCard);
        Assert.Contains("BDAY:19900101", vCard);
    }

    [Fact]
    public void GenerateVCard_ContainsCorrectStructure()
    {
        // Arrange
        string name = "Alice Johnson";
        string email = "alice@example.com";
        DateTime dateOfBirth = new DateTime(1992, 12, 25);

        // Act
        string vCard = _qrCodeService.GenerateVCard(name, email, dateOfBirth);
        var lines = vCard.Split(Environment.NewLine);

        // Assert
        Assert.NotEmpty(lines);
        Assert.Equal("BEGIN:VCARD", lines[0].Trim());
        Assert.Contains(lines, line => line.Contains("VERSION:3.0"));
        Assert.Contains(lines, line => line.Contains($"FN:{name}"));
        Assert.Contains(lines, line => line.Contains($"EMAIL:{email}"));
        Assert.Contains(lines, line => line.Contains("BDAY:19921225"));
        Assert.Equal("END:VCARD", lines[^1].Trim());
    }

    [Fact]
    public void GenerateQRCodeBytes_WithValidInput_ReturnsByteArray()
    {
        // Arrange
        string name = "Bob Wilson";
        string email = "bob@example.com";
        DateTime dateOfBirth = new DateTime(1988, 7, 10);

        // Act
        byte[] qrCodeBytes = _qrCodeService.GenerateQRCodeBytes(name, email, dateOfBirth);

        // Assert
        Assert.NotNull(qrCodeBytes);
        Assert.True(qrCodeBytes.Length > 0, "Generated byte array is empty");
    }

    [Fact]
    public void GenerateQRCodeBytes_ReturnsPngFormat()
    {
        // Arrange
        string name = "Carol Davis";
        string email = "carol@example.com";
        DateTime dateOfBirth = new DateTime(1995, 6, 15);

        // Act
        byte[] qrCodeBytes = _qrCodeService.GenerateQRCodeBytes(name, email, dateOfBirth);

        // Assert
        // PNG files start with this magic number
        byte[] pngMagic = { 0x89, 0x50, 0x4E, 0x47 };
        for (int i = 0; i < pngMagic.Length; i++)
        {
            Assert.Equal(pngMagic[i], qrCodeBytes[i]);
        }
    }

    [Theory]
    [InlineData("John", "john@test.com", "1990-01-01")]
    [InlineData("Jane", "jane@test.com", "1985-12-25")]
    [InlineData("Bob", "bob@test.com", "2000-06-15")]
    public void GenerateQRCode_WithMultipleInputs_ReturnsValidPaths(string name, string email, string dobString)
    {
        // Arrange
        DateTime dob = DateTime.Parse(dobString);

        // Act
        string filePath = _qrCodeService.GenerateQRCode(name, email, dob);

        // Assert
        Assert.NotNull(filePath);
        Assert.NotEmpty(filePath);
        Assert.True(filePath.Contains("QRCode_"));

        // Cleanup
        if (File.Exists(filePath))
        {
            File.Delete(filePath);
        }
    }
}
